config/routes.rb
Rails.application.routes.draw do
	root "static_pages#home"
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  
  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    return unless logged_in?
    @micropost = current_user.microposts.build
    @feed_items = current_user.feed.paginate(page: params[:page], per_page: 10)
  end

  def help; end

  def about; end

  def contact; end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide :title, t("about") %>
<h1><%= t "about" %></h1>
<p>
    <%= link_to "Ruby On Rails", Settings.links.railstutorial %> 
    <%= t("texts.is") %>
    <%= link_to t("texts.book"), Settings.links.book %> 
    <%= t("texts.and") %>
    <%= link_to t("texts.guide"), Settings.links.guide %>
    <%= t("texts.dev") %>
    <%= link_to "Ruby on Rails", Settings.links.ruby_on_rails %>
    <%= t("texts.sample") %>
</p>

app/views/static_pages/contact.html.erb
<% provide :title, t("contact") %>
<h1>Contact</h1>
<p>
    <%= t("texts.contact_intro") %>
    <%= link_to t("texts.here"), Settings.links.contact %>
</p>

app/views/static_pages/help.html.erb
<% provide :title, t("help") %>
<h1><%= t("help") %></h1>
<p>
    <%= t("texts.help_open") %>
    <%= link_to t("title.help"), Settings.links.help %> 
    <%= t("texts.help_close")  %>
    <%= link_to t("texts.here"), Settings.links.guide %>
    <%= t "dev" %>
    <%= link_to "Ruby on Rails", Settings.links.ruby_on_rails %>
    <%= t("texts.sample")%>
</p>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render "shared/user_info" %>
      </section>
       <section class="stats">
        <%= render "shared/stats" %>
      </section>
      <section class="micropost_form">
        <%= render "shared/micropost_form" %>
      </section>
    </aside>
    
    <div class="col-md-8">
      <h3><%= t("micropost.name")%></h3>
      <%= render "shared/feed" %>
    </div>
  </div>
  <% else %>

<div class="center jumbotron">
  <% provide :title, t("home") %>
<h1><%= t "sampleApp" %></h1>
<p>
  <div><%= t ("texts.home_intro") %></div>
  <%= link_to t("texts.sample_app"), Settings.links.ruby_on_rails %>
  <div>
  <%= link_to t("signUpNow"), signup_path, class: "btn btn-lg btn-primary" %>
  </div>
</div>

<%= link_to image_tag("rails.png", alt: "Rails logo"),
            Settings.links.ruby_on_rails %>
</p>
<% end %>